=== almightyeric/TCOM-514-Project2/Shengwei_Zhao.dtd
<!ELEMENT Shengwei_Zhao (personal_info, education_background, personal_interests?)>

<!ELEMENT personal_info (name, age, gender)>
<!ELEMENT education_background (degree, university, major, courses_2013fall)>
<!ELEMENT personal_interests (favorite_movie, favorite_author, favorite_city?, favorite_computer?)>

<!ELEMENT courses_2013fall (course+)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT degree (#PCDATA)>
<!ELEMENT university (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT favorite_movie (#PCDATA)>
<!ELEMENT favorite_author (#PCDATA)>
<!ELEMENT favorite_city (#PCDATA)>
<!ELEMENT favorite_computer (#PCDATA)>
<!ATTLIST course type CDATA #REQUIRED >
<!ATTLIST name country CDATA #FIXED "China">

=== almightyeric/TCOM-514-Project2/homework2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="homework2.xsl"?>

<!DOCTYPE Shengwei_Zhao SYSTEM "Shengwei_Zhao.dtd">
<Shengwei_Zhao >

	<personal_info>
		<name country="China">Shengwei Zhao</name>
		<age>24</age>
		<gender>male</gender>
	</personal_info>
	
	<education_background >
  		<degree >master</degree> 
  		<university>University of Pennsylvania</university> 
  		<major>Computer Networking and Telecommunications</major> 
  		<courses_2013fall>
  			<course type="mandatory">TCOM 514</course>
  			<course type="selective">EAS 546</course>
  		</courses_2013fall>      
	</education_background>

	<personal_interests >
  		<favorite_movie >Harry Potter</favorite_movie> 
  		<favorite_author>J K. Rowling</favorite_author> 
  		<favorite_city>Philadelphia</favorite_city> 
  		<favorite_computer>Macbook Pro</favorite_computer> 
	</personal_interests>

</Shengwei_Zhao>
